-- CreateEnum
CREATE TYPE "ArchiveWorkflowStatus" AS ENUM (
  'DRAFT',
  'PENDING_REVIEW',
  'ARCHIVED',
  'MODIFIED',
  'BORROWED',
  'RETURNED',
  'DESTROYED'
);

-- CreateEnum
CREATE TYPE "ArchiveVersionStatus" AS ENUM (
  'DRAFT',
  'FINAL',
  'ABOLISHED'
);

-- AlterTable
ALTER TABLE "physical_archives"
ADD COLUMN "archiveCode" TEXT,
ADD COLUMN "subtitle" TEXT,
ADD COLUMN "categoryPath" TEXT,
ADD COLUMN "categoryId" TEXT,
ADD COLUMN "language" TEXT,
ADD COLUMN "carrierType" TEXT,
ADD COLUMN "archiveForm" TEXT,
ADD COLUMN "responsibleParty" TEXT,
ADD COLUMN "responsibleCode" TEXT,
ADD COLUMN "filingDate" TIMESTAMP(3),
ADD COLUMN "effectiveDate" TIMESTAMP(3),
ADD COLUMN "invalidDate" TIMESTAMP(3),
ADD COLUMN "attachmentCount" INTEGER,
ADD COLUMN "summary" TEXT,
ADD COLUMN "keywords" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "subjectTerms" TEXT,
ADD COLUMN "documentGenre" TEXT,
ADD COLUMN "urgencyLevel" TEXT,
ADD COLUMN "workflowStatus" "ArchiveWorkflowStatus" NOT NULL DEFAULT 'DRAFT',
ADD COLUMN "filingDepartment" TEXT,
ADD COLUMN "transferPerson" TEXT,
ADD COLUMN "transferDate" TIMESTAMP(3),
ADD COLUMN "receiver" TEXT,
ADD COLUMN "receiveDate" TIMESTAMP(3),
ADD COLUMN "storageLocation" TEXT,
ADD COLUMN "shelfNo" TEXT,
ADD COLUMN "volumeNo" TEXT,
ADD COLUMN "itemNo" TEXT,
ADD COLUMN "appraisalStatus" TEXT,
ADD COLUMN "appraiser" TEXT,
ADD COLUMN "appraisalDate" TIMESTAMP(3),
ADD COLUMN "electronicFileId" TEXT,
ADD COLUMN "originalFileName" TEXT,
ADD COLUMN "fileExtension" TEXT,
ADD COLUMN "fileSizeBytes" BIGINT,
ADD COLUMN "fileStoragePath" TEXT,
ADD COLUMN "storageMethod" TEXT,
ADD COLUMN "fileMd5" TEXT,
ADD COLUMN "ocrText" TEXT,
ADD COLUMN "thumbnailPath" TEXT,
ADD COLUMN "transferStatus" TEXT,
ADD COLUMN "digitizationStatus" TEXT,
ADD COLUMN "versionNo" TEXT DEFAULT 'V1.0',
ADD COLUMN "revisionNo" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN "previousVersionNo" TEXT,
ADD COLUMN "versionRemark" TEXT,
ADD COLUMN "versionStatus" "ArchiveVersionStatus" NOT NULL DEFAULT 'FINAL',
ADD COLUMN "isCurrentVersion" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "versionHistory" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "parentArchiveId" TEXT,
ADD COLUMN "rootArchiveId" TEXT,
ADD COLUMN "relatedArchiveIds" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "predecessorArchiveId" TEXT,
ADD COLUMN "successorArchiveId" TEXT,
ADD COLUMN "replacedArchiveId" TEXT,
ADD COLUMN "copiedFromArchiveId" TEXT,
ADD COLUMN "ownerName" TEXT,
ADD COLUMN "ownerDepartment" TEXT,
ADD COLUMN "accessLevel" TEXT,
ADD COLUMN "accessPolicy" TEXT,
ADD COLUMN "watermarkConfig" TEXT,
ADD COLUMN "encryptionAlgorithm" TEXT,
ADD COLUMN "encryptionStatus" TEXT,
ADD COLUMN "tamperProofHash" TEXT,
ADD COLUMN "creatorDepartment" TEXT,
ADD COLUMN "updatedById" TEXT,
ADD COLUMN "reviewer" TEXT,
ADD COLUMN "reviewedAt" TIMESTAMP(3),
ADD COLUMN "reviewComment" TEXT,
ADD COLUMN "filer" TEXT,
ADD COLUMN "filedAt" TIMESTAMP(3),
ADD COLUMN "destroyer" TEXT,
ADD COLUMN "destroyedAt" TIMESTAMP(3),
ADD COLUMN "destroyReason" TEXT,
ADD COLUMN "lastAccessedBy" TEXT,
ADD COLUMN "lastAccessedAt" TIMESTAMP(3),
ADD COLUMN "customText1" TEXT,
ADD COLUMN "customText2" TEXT,
ADD COLUMN "customText3" TEXT,
ADD COLUMN "customNumber" DOUBLE PRECISION,
ADD COLUMN "customDate" TIMESTAMP(3),
ADD COLUMN "extraJson" JSONB;

-- CreateIndex
CREATE INDEX "physical_archives_workflowStatus_idx" ON "physical_archives"("workflowStatus");
